class wagon{
    constructor(id, number, wagon_type, volume, created_at){
        this.id = id,
        this.number = number,
        this.wagon_type = wagon_type,
        this.volume = volume,
        this.created_at = created_at
    }

}
class wagon_actual_passports{
    constructor(
        id,
        effective_date,
        is_actual,
        name,
        short_name,
        owner_contractor_legal_short_name,
        manager_contractor_work_name,
        manager_contractor_legal_short_name,
        agreement_number,
        registrar_short_about,
        ros_owners_tenant,
        etran_tenant_from_gvc,
        general_group_name,
        lessor_contractor_work_name,
        lessor_contractor_legal_short_name,
        dislocation_operator_by_proxy_name,
        etran_owner_name,
        created_at,
        wagon)
        {
        this.id = id, 
        this.effective_date = effective_date,
        this.is_actual = is_actual, 
        this.name = name,
        this.short_name= short_name,
        this.owner_contractor_legal_short_name = owner_contractor_legal_short_name,
        this.manager_contractor_work_name = manager_contractor_work_name,
        this.manager_contractor_legal_short_name = manager_contractor_legal_short_name,
        this.agreement_number = agreement_number,
        this.registrar_short_about = registrar_short_about,
        this.ros_owners_tenant = ros_owners_tenant,
        this.etran_tenant_from_gvc = etran_tenant_from_gvc,
        this.general_group_name = general_group_name,
        this.lessor_contractor_work_name = lessor_contractor_work_name,
        this.lessor_contractor_legal_short_name = lessor_contractor_legal_short_name,
        this.dislocation_operator_by_proxy_name = dislocation_operator_by_proxy_name,
        this.etran_owner_name = etran_owner_name,
        this.created_at = created_at,
        this.wagon = wagon
        }
}
class wagon_actual_passports{
    constructor(
        id,
        info_source_name ,
        build_date,
        factory_number,
        factory_code,
        factory_name,
        registration_date,
        owner_contractor_code,
        owner_home_station_code,
        owner_home_station_name,
        owner_home_road_name,
        length,
        capacity,
        light_weight,
        wagon_type_code,
        prev_wagon_number,
        last_cr_date,
        last_cr_depot_code,
        last_cr_depot_name,
        last_cr_road_name,
        last_dr_date,
        last_dr_depot_code,
        last_dr_depot_name,
        last_dr_road_name,
        next_planned_repair_date,
        next_planned_repair_short_name,
        lifetime,
        lifetime_prolongation_doc_date,
        lifetime_prolongation_doc_number,
        dimension_name,
        body_material_name,
        auto_coupling_name,
        air_distributor_name,
        draft_gear_name,
        auto_mode_name,
        carriage_model_name,
        lease_expire_date,
        last_review_date,
        last_review_depot_code,
        last_review_depot_name,
        last_examination_date,
        last_examination_depot_code,
        last_examination_depot_name,
        calculate_next_cr_date,
        caliber,
        model,
        country_sobstv,
        days_before_date_plan_repair,
        owner_home_road_code,
        last_cr_road_code,
        last_dr_road_code,
        created_at,
        wagon
    ){
        this.id = id,
        this.info_source_name = info_source_name,
        this. build_date = build_date,
        this.factory_number = factory_number,
        this.factory_code = factory_code,
        this.factory_name = factory_name,
        this.registration_date = registration_date,
        this.owner_contractor_code = owner_contractor_code,
        this.owner_home_station_code = owner_home_station_code,
        this.owner_home_station_name = owner_home_station_name,
        this.owner_home_road_name = owner_home_road_name,
        this.length = length,
        this.capacity = capacity,
        this.light_weight = light_weight,
        this.wagon_type_code = wagon_type_code,
        this.prev_wagon_number = prev_wagon_number,
        this.last_cr_date = last_cr_date,
        this.last_cr_depot_code = last_cr_depot_code,
        this.last_cr_depot_name = last_cr_depot_name,
        this.last_cr_road_name = last_cr_road_name,
        this.last_dr_date = last_dr_date,
        this.last_dr_depot_code = last_dr_depot_code,
        this.last_dr_depot_name = last_dr_depot_name,
        this.last_dr_road_name = last_dr_road_name,
        this.next_planned_repair_date = next_planned_repair_date,
        this.next_planned_repair_short_name = next_planned_repair_short_name,
        this.lifetime = lifetime,
        this.lifetime_prolongation_doc_date = lifetime_prolongation_doc_date,
        this.lifetime_prolongation_doc_number = lifetime_prolongation_doc_number,
        this.dimension_name = dimension_name,
        this.body_material_name = body_material_name,
        this.air_distributor_name = air_distributor_name,
        this.draft_gear_name = draft_gear_name,
        this.auto_mode_name = auto_mode_name,
        this.carriage_model_name = carriage_model_name,
        this.lease_expire_date = lease_expire_date,
        this.last_review_date = last_review_date,
        this.last_review_depot_code = last_review_depot_code,
        this.last_review_depot_name = last_review_depot_name,
        this.last_examination_date = last_examination_date,
        this.last_examination_depot_code = last_examination_depot_code,
        this.last_examination_depot_name = last_examination_depot_name,
        this.calculate_next_cr_date = calculate_next_cr_date,
        this.caliber = caliber,
        this.model = model,
        this.country_sobstv = country_sobstv,
        this.days_before_date_plan_repair = days_before_date_plan_repair,
        this.owner_home_road_code = owner_home_road_code,
        this.last_cr_road_code = last_cr_road_code,
        this.last_dr_road_code = last_dr_road_code,
        this.created_at = created_at,
        this.wagon = wagon
    }
}
class wagon_rest_runs{
    constructor(
        id,
        actual_run,
        rest_run,
        run_limit,
        created_at,
        wagon
    )
    {
        this.id = id,
        this.actual_run = actual_run,
        this.rest_run = rest_run,
        this.run_limit = run_limit,
        this.created_at = created_at,
        this.wagon = wagon

    }
}
class wagon_last_repairs{
    constructor(
        id,
        faulty_date,
        vu_23_number,
        set_off_station_code,
        set_off_station_name,
        set_off_road_name,
        repair_type_short_name,
        faultiness1_name,
        faultiness2_name,
        faultiness3_name,
        depot_code,
        depot_name,
        depot_road_name,
        repair_date,
        vu_36_number,
        sf_number,
        sf_date,
        tr_depot_name,
        tr_depot_road_name,
        tr_malfunction,
        tr_data,
        station_name,
        calc_planned_repair_date,
        tr_depot_road_code,
        depot_road_code,
        set_off_road_code,
        created_at,
        wagon
    ){
        this.id = id,
        this.faulty_date = faulty_date,
        this.vu_23_number = vu_23_number,
        this.set_off_station_code = set_off_station_code,
        this.set_off_station_name = set_off_station_name,
        this.set_off_road_name = set_off_road_name,
        this.repair_type_short_name = repair_type_short_name,
        this.faultiness1_name = faultiness1_name,
        this.faultiness2_name = faultiness2_name,
        this.faultiness3_name = faultiness3_name,
        this.depot_code = depot_code,
        this.depot_name = depot_name,
        this.depot_road_name = depot_road_name,
        this.repair_date = repair_date,
        this.vu_36_number = vu_36_number,
        this.sf_number = sf_number,
        this.sf_date = sf_date,
        this.tr_depot_name = tr_depot_name,
        this.tr_depot_road_name = tr_depot_road_name,
        this.tr_malfunction = tr_malfunction,
        this.tr_data = tr_data,
        this.station_name = station_name,
        this.calc_planned_repair_date = calc_planned_repair_date,
        this.tr_depot_road_code = tr_depot_road_code,
        this.depot_road_code = depot_road_code,
        this.set_off_road_code = set_off_road_code,
        this. created_at = created_at,
        this.wagon = wagon
    }
}